Repository pagopa/pagopa-gps-mbd-service, pull requests merged in 2024-12, with the labels that each got.

#2 chore: Fix app name
  .github/workflows/cd_deploy_with_github_runner.yml
Labels: size/small

#3 chore: Fix deploy
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#7 fix: Integration tests
  .github/workflows/ci_integration_test.yml
  .identity/01_github_environment.tf
  integration-test/src/step_definitions/support/common.js
Labels: size/small, skip

#6 [PPANTT-194] feat: Add performance test
  .devops/performance-test-pipelines.yml
  performance-test/src/dev.environment.json
  performance-test/src/gps-mbd-service_test.js
  performance-test/src/local.environment.json
  performance-test/src/main_scanario.js
  performance-test/src/modules/client.js
  performance-test/src/test-types/constant.json
  performance-test/src/uat.environment.json
Labels: skip

#8 feat: Change APIM product
  infra/99_locals.tf
  integration-test/src/step_definitions/gps-mbs-service_steps.js
  openapi/openapi.json
  src/main/java/it/gov/pagopa/mbd/gps/service/mapper/ConvertMbdPaymentOptionRequestToMbdPaymentOptionResponse.java
  src/main/java/it/gov/pagopa/mbd/gps/service/model/PaymentOption.java
  src/test/java/it/gov/pagopa/mbd/gps/service/controller/MbdGpsControllerTest.java
Labels: minor, size/small

#9 fix: stamptype value from st to 01
  src/main/java/it/gov/pagopa/mbd/gps/service/mapper/ConvertMbdPaymentOptionRequestToMbdPaymentOptionResponse.java
Labels: size/small

#10 fix: Tests
  integration-test/src/step_definitions/gps-mbs-service_steps.js
  src/test/java/it/gov/pagopa/mbd/gps/service/controller/MbdGpsControllerTest.java
Labels: size/small, skip
